# vim: syntax=python expandtab
# mwc global configuration file


#########################
# Run configuration
#########################
inputdir: "input"
input_fn_pattern: "{sample}_R{readpair}.fastq.gz" 
outdir: "output_dir"
dbdir: "databases"

#########################
# Steps included
#########################
qc_reads: True
taxonomic_profile: True
mocat2: False

#########################
# Read quality assessment
#########################
bbduk_minlen: 30
bbduk_qtrim: "rl"
bbduk_trimq: 20
bbduk_ktrim: "r"
bbduk_k: 30
bbduk_mink: 11
bbduk_hdist: 1
bbduk_trimbyoverlap: "trimbyoverlap"
bbduk_trimpairsevenly: "trimpairsevenly"

#########################
# Taxonomic profiling
#########################


#########################
# MOCAT 2
#########################
mocat2_sample_file: ""
mocat2_config_file: ""
mocat2_email: "mwc@mailinator.com"
