# vim: syntax=python expandtab
# mwc global configuration file


#########################
# Run configuration
#########################
inputdir: "input"
input_fn_pattern: "{sample}_R{readpair}.fastq.gz" 
outdir: "output_dir"
dbdir: "databases"       # Databases will be downloaded to this dir, if requested


#########################
# Pipeline steps included
#########################
qc_reads: True
remove_human: True
mappers:
    bowtie2: True
taxonomic_profile:
    kaiju: True


#########################
# Read quality assessment
#########################
bbduk:
    minlen: 30
    qtrim: "rl"
    trimq: 20
    ktrim: "r"
    k: 30
    mink: 11
    hdist: 1
    trimbyoverlap: "trimbyoverlap"
    trimpairsevenly: "trimpairsevenly"
remove_human:
    hg19_path: ""        # Path to folder containing the BBMap index for hg19
    minid: 0.95
    maxindel: 3
    minhits: 2
    bandwidthratio: 0.16
    bandwidth: 12
    qtrim: "rl"
    trimq: 10
    quickmatch: "quickmatch"
    fast: "fast"
    untrim: "untrim"

#########################
# Mappers
#########################
bowtie2:
    db_prefix: ""         # Full path to Bowtie2 index (not including file extension)
    extra: ""             # Extra bowtie2 commandline parameters


#########################
# Taxonomic profiling
#########################
kaiju:
    db: ""               # Path to Kaiju DB file
    nodes: ""            # Path to Kaiju taxonomy nodes.dmp
    names: ""            # Path to Kaiju taxonomy names.dmp
