# vim: syntax=python expandtab
#
#     StaG Metagenomic Workflow Collaboration
#                 configuration file
#
# Configuration settings marked with [Required] are only required if the
# pipeline step for that setting is included. Set which steps to include
# under the "Pipeline steps included" heading. The default settings are to
# only run read preprocessing steps.


#########################
# Run configuration
#########################
inputdir: "input"
input_fn_pattern: "{sample}_R{readpair}.fastq.gz" 
outdir: "output_dir"
dbdir: "databases"       # Databases will be downloaded to this dir, if requested


#########################
# Pipeline steps included
#########################
qc_reads: True
remove_human: True
sketch_compare: False
mappers:
    bbmap: False
    bowtie2: False
taxonomic_profile:
    centrifuge: False
    kaiju: False
    metaphlan2: False
antibiotic_resistance: False


#########################
# Read quality assessment
#########################
bbduk:
    minlen: 30
    qtrim: "rl"
    trimq: 20
    ktrim: "r"
    k: 30
    mink: 11
    hdist: 1
    trimbyoverlap: "trimbyoverlap"
    trimpairsevenly: "trimpairsevenly"
remove_human:
    hg19_path: ""        # [Required] Path to folder containing the BBMap index for hg19
    minid: 0.95
    maxindel: 3
    minhits: 2
    bandwidthratio: 0.16
    bandwidth: 12
    qtrim: "rl"
    trimq: 10
    quickmatch: "quickmatch"
    fast: "fast"
    untrim: "untrim"

#########################
# Mappers
#########################
bbmap:
    db_name: ""           # [Required] Custom name for BBMap database
    db_path: ""           # [Required] Path to BBMap database (folder should contain a 'ref' folder)
    min_id: 0.76          # Minimum id for read alignment, BBMap default is 0.76
    extra: ""             # Extra BBMap command line parameters
bowtie2:
    db_prefix: ""         # [Required] Full path to Bowtie2 index (not including file extension)
    extra: ""             # Extra bowtie2 commandline parameters


#########################
# Taxonomic profiling
#########################
centrifuge:
    db_prefix: ""        # [Required] Path to Centrifuge DB index (not including file extension)

kaiju:
    db: ""               # [Required] Path to Kaiju DB file
    nodes: ""            # [Required] Path to Kaiju taxonomy nodes.dmp
    names: ""            # [Required] Path to Kaiju taxonomy names.dmp

metaphlan2:
    mpa_pkl: ""          # [Required] Path to MetaPhlAn2 pickle file: mpa_v20_m200.pkl
    bt2_db_prefix: ""    # [Required] Path to MetaPhlAn2 Bowtie2 index prefix: /path/to/mpa_v20_m200 (no file extension)
    extra: ""            # Extra command line arguments for metaphlan2.py


#########################
# Antibiotic Resistance
#########################
megares:
    db_path: ""          # [Required] Path to folder containing MEGARes BBMap index
    min_id: 0.91
    max_indel: 1600      # BBMap default is 16000
    extra: ""            # Extra BBMap commandline parameters
